style: {
  fill: transparent
}

classes: {
  invisible: {
    style.opacity: 0
    label: a
  }
  vector-store: {
    label: "Vector Store"
  }
  scylla: {
    label: "Scylla"
    shape: cylinder
  }
}

direction: right

scylla.class: scylla

vector-store: {
  class: vector-Store

  httpd
  db-index
  db
  monitor-items
  monitor-indexes
  index: {
    USearch.height: 200
  }

  db <- monitor-indexes
  db-index -> monitor-items
  monitor-items -> index: Modify
  httpd -> index: ANN Search
}

scylla -- vector-store.db: CQL
scylla -- vector-store.db-index: CQL/CDC
scylla -> vector-store.httpd: HTTP
