#!/bin/bash

set -e

logfile=$1
[[ -f $logfile ]] || (echo log file invalid or not provided; exit 1)

dir=$(dirname $logfile)
[[ -z $dir ]] && dir=.

base=$(basename $logfile .log)

conc_file=$dir/${base}-concurrency.csv
qps_file=$dir/${base}-qps.csv
p50_file=$dir/${base}-p50.csv
p99_file=$dir/${base}-p99.csv
csv_file=$dir/${base}.csv

echo Concurrency > $conc_file
echo QPS > $qps_file
echo P50 > $p50_file
echo P99 > $p99_file
cat $logfile | ansi2txt | grep concurrency | sed -e 's/.*--concurrency \([0-9]*\).*/\1/' >> $conc_file
cat $logfile | ansi2txt | grep "QPS:" | sed -e 's/.*QPS: \(.*\)/\1/' >> $qps_file
cat $logfile | ansi2txt | grep "latency P50:" | sed -e 's/.*latency P50: \(.*\)ms/\1/' >> $p50_file
cat $logfile | ansi2txt | grep "latency P99:" | sed -e 's/.*latency P99: \(.*\)ms/\1/' >> $p99_file
paste -d, $conc_file $qps_file $p50_file $p99_file > $csv_file
